"use client";
import {useEffect,useMemo,useState} from "react";

const editions={
  keepsake:{name:"The Keepsake",description:"A quiet place for their portrait and the memories you hold close.",base:["30 mm custom pet portrait medallion","Walnut keepsake box"],defaults:{archivalPhoto:false,nameYearsCard:false,hairVial:false,memoryPouch:false,memoryCard:false,backEngraving:false,chain:false},options:["archivalPhoto","nameYearsCard","memoryCard","backEngraving"]},
  complete:{name:"The Complete",description:"A considered memorial box with the pieces that tell their story.",base:["30 mm custom pet portrait medallion","Walnut keepsake box","Archival photo","Name & Years card"],defaults:{archivalPhoto:true,nameYearsCard:true,hairVial:false,memoryPouch:false,memoryCard:false,backEngraving:false,chain:false},options:["hairVial","memoryPouch","memoryCard","backEngraving"]},
  wear:{name:"Wear & Keep",description:"The Complete keepsake, with a matching chain to carry them with you.",base:["Everything in The Complete","Matching chain"],defaults:{archivalPhoto:true,nameYearsCard:true,hairVial:false,memoryPouch:false,memoryCard:false,backEngraving:false,chain:true},options:["hairVial","memoryPouch","memoryCard","backEngraving","chainLength"]}
};
const productLibrary=[
  {family:"WEAR",id:"portrait-pendant",name:"Portrait Pendant",note:"Their portrait, close to you.",finish:true,options:["45 cm chain","50 cm chain"]},
  {family:"WEAR",id:"portrait-bracelet",name:"Portrait Bracelet",note:"A quiet everyday piece.",finish:true,options:["16 cm","18 cm","20 cm"]},
  {family:"CARRY",id:"leather-travel-tag",name:"Leather Travel Tag",note:"Take them wherever you go.",finish:false,options:["Mocha","Ivory","Etoupe"]},
  {family:"CARRY",id:"bag-charm",name:"Bag Charm",note:"A small piece of them, with you.",finish:true,options:["Classic","Mini"]},
  {family:"KEEP",id:"portrait-coin",name:"Portrait Coin",note:"Their portrait, made permanent.",finish:true,options:["30 mm","35 mm"]},
  {family:"KEEP",id:"paw-keepsake",name:"Paw Keepsake",note:"Made from their actual paw print.",requires:"paw",finish:true,options:["30 mm","35 mm"]}
];
const optionMeta={archivalPhoto:{label:"Archival photo",help:"A printed photograph kept inside the box."},nameYearsCard:{label:"Name & Years card",help:"A small card with their name and years together."},hairVial:{label:"Hair keepsake vial",help:"A glass vial for a small, meaningful hair keepsake."},memoryPouch:{label:"Memory pouch",help:"A small pouch for other meaningful keepsakes."},memoryCard:{label:"Memory card",help:"A card for a short personal message."},backEngraving:{label:"Back engraving",help:"Add a private phrase or message to the back of the medallion."}};
function Choice({active,onClick,children}){return <button type="button" className={"choice-pill "+(active?"selected":"")} onClick={onClick}>{children}</button>}
function IncludedBadge({included}){return <span className={"included-badge "+(included?"is-included":"is-optional")}>{included?"Included":"Optional"}</span>}

export default function OrderBuilder({metal="gold",setMetal,petName="",years="",petIdentity=null,onBack}){
  const [selectedProduct,setSelectedProduct]=useState("portrait-coin"),[productOption,setProductOption]=useState("30 mm"),[edition,setEdition]=useState("complete"),[finish,setFinish]=useState(metal||"gold"),[contents,setContents]=useState(editions.complete.defaults),[memoryText,setMemoryText]=useState(""),[backEngravingType,setBackEngravingType]=useState("none"),[presetPhrase,setPresetPhrase]=useState("Always with me"),[customBackText,setCustomBackText]=useState(""),[chainLength,setChainLength]=useState("45 cm"),[email,setEmail]=useState("");
  const config=editions[edition];
  useEffect(()=>{setFinish(metal||"gold")},[metal]);
  function chooseEdition(next){setEdition(next);setContents(editions[next].defaults);setBackEngravingType("none");setMemoryText("");setCustomBackText("");setChainLength(next==="wear"?"45 cm":"")}
  function chooseFinish(next){setFinish(next);setMetal?.(next)}
  function toggleContent(key,value){setContents(prev=>({...prev,[key]:value}))}
  function chooseEngravingType(next){setBackEngravingType(next);setContents(prev=>({...prev,backEngraving:next!=="none"}))}
  const canMemoryCard=contents.memoryCard;
  const engravingLabel=backEngravingType==="preset"?presetPhrase:backEngravingType==="custom"?(customBackText||"Custom text"):"No engraving";
  const includedItems=useMemo(()=>{const items=[...config.base];if(edition==="keepsake"&&contents.archivalPhoto)items.push("Archival photo");if(edition==="keepsake"&&contents.nameYearsCard)items.push("Name & Years card");if(contents.hairVial)items.push("Hair keepsake vial");if(contents.memoryPouch)items.push("Memory pouch");if(contents.memoryCard)items.push("Memory card");if(contents.backEngraving)items.push("Back engraving");return items},[config.base,contents,edition]);
  const ready=petName.trim().length>0&&email.trim().length>3,displayOptions=config.options.filter(key=>key!=="chainLength");
  return <section className="order-builder configurable-builder" aria-labelledby="finish-title">
    <p className="step">04 · CHOOSE A PIECE</p><h1 id="finish-title">Now make it theirs.</h1><p className="muted finish-intro">{petIdentity?.status==="portrait_ready" ? (petName+"’s Pet Identity is ready. Choose where they go next.") : "Start with a signature piece, then personalize the details."}</p>
    {petIdentity?.status==="portrait_ready"&&<section className="identity-ready" aria-label="Pet Identity ready"><div><p className="section-label">PET IDENTITY READY</p><h2>Made for {petName}.</h2><p>Your approved portrait can now move with {petName} across Evlenne — without uploading their photo again.</p></div><div className="identity-ready-meta"><span>PORTRAIT <b>READY</b></span><span>PAW <b>ADD LATER</b></span><span>FUR <b>ADD LATER</b></span></div></section>}
    {petIdentity?.status==="portrait_ready"&&<section className="product-library" aria-labelledby="library-heading"><div className="builder-section-heading"><p className="section-label">MADE FOR {petName ? petName.toUpperCase() : "YOUR PET"}</p><h2 id="library-heading">Choose where they go next.</h2><p className="builder-note">One Pet Identity, ready across the Evlenne product library.</p></div><div className="product-library-grid">{productLibrary.map(item=>{const locked=item.requires==="paw"&&!petIdentity?.assets?.paw;return <button type="button" key={item.id} disabled={locked} className={"library-product "+(selectedProduct===item.id?"selected ":"")+(locked?"locked":"")} onClick={()=>{if(!locked){setSelectedProduct(item.id);setProductOption(item.options?.[0]||"")}}}><small>{item.family}</small><strong>{item.name}</strong><span>{locked?"Add paw print to unlock":item.note}</span><em>{selectedProduct===item.id?"Selected":"Use "+petName}</em></button>})}</div></section>}
    {petIdentity?.status==="portrait_ready"&&(()=>{const product=productLibrary.find(item=>item.id===selectedProduct)||productLibrary[0];return <section className="builder-section product-config" aria-labelledby="product-config-heading"><p className="section-label">PRODUCT DETAILS</p><h2 id="product-config-heading">{product.name} for {petName}.</h2><p className="builder-note">Their approved Pet Identity portrait is already attached. No re-upload needed.</p>{product.finish&&<div className="finish-swatches compact-finishes"><button type="button" className={finish==="gold"?"selected":""} onClick={()=>chooseFinish("gold")}><span className="finish-swatch gold-swatch"/><strong>Gold</strong></button><button type="button" className={finish==="silver"?"selected":""} onClick={()=>chooseFinish("silver")}><span className="finish-swatch silver-swatch"/><strong>Silver</strong></button></div>}<div className="product-option-row">{product.options?.map(option=><Choice key={option} active={productOption===option} onClick={()=>setProductOption(option)}>{option}</Choice>)}</div><div className="identity-attachment"><span>PET IDENTITY</span><strong>{petName} · Portrait ready ✓</strong></div><div className="product-next"><strong>{product.name}</strong><span>{productOption}{product.finish?" · "+(finish==="silver"?"Silver":"Gold"):""}</span><button type="button" className="checkout-preview">Continue with {petName} →</button></div></section>})()}
    {false&&<section className="builder-section edition-section" aria-labelledby="edition-heading"><div className="builder-section-heading"><p className="section-label">CHOOSE YOUR EDITION</p><h2 id="edition-heading">A thoughtful place for what matters.</h2></div><div className="edition-grid">{Object.entries(editions).map(([id,item],index)=><button type="button" key={id} className={"edition-card "+(edition===id?"selected":"")} onClick={()=>chooseEdition(id)}><span className="edition-number">0{index+1}</span><strong>{item.name}</strong><span className="edition-description">{item.description}</span><span className="edition-contents">{item.base.map(content=><em key={content}>✓ {content}</em>)}</span><span className="edition-select">{edition===id?"Selected":"Choose edition"}</span></button>)}</div></section>}
    <div className="legacy-keepsake-builder"><section className="builder-section" aria-labelledby="finish-heading"><p className="section-label">FINISH</p><h2 id="finish-heading">Choose the finish.</h2><div className="finish-swatches"><button type="button" className={finish==="gold"?"selected":""} onClick={()=>chooseFinish("gold")}><span className="finish-swatch gold-swatch"/><strong>Gold</strong><small>Warm champagne gold</small></button><button type="button" className={finish==="silver"?"selected":""} onClick={()=>chooseFinish("silver")}><span className="finish-swatch silver-swatch"/><strong>Silver</strong><small>Quiet brushed silver</small></button></div></section>
    <section className="builder-section" aria-labelledby="inside-heading"><p className="section-label">WHAT WOULD YOU LIKE INSIDE?</p><h2 id="inside-heading">Make room for their story.</h2><div className="contents-list">{displayOptions.map(key=>{const meta=optionMeta[key],included=!!contents[key];return <div className="content-option" key={key}><div className="content-option-copy"><strong>{meta.label}</strong><span>{meta.help}</span></div><div className="content-option-actions"><IncludedBadge included={included}/><div className="choice-pills"><Choice active={included} onClick={()=>toggleContent(key,true)}>Include</Choice><Choice active={!included} onClick={()=>toggleContent(key,false)}>Skip</Choice></div></div></div>})}</div><p className="builder-note">This edition includes its core pieces by default. Optional pieces can be added or skipped above.</p></section>
    {canMemoryCard&&<div className="conditional-card"><label>Memory card <span className="optional">optional</span><span className="field-help">A short memory, phrase or message.</span><textarea maxLength={160} value={memoryText} onChange={e=>setMemoryText(e.target.value)} placeholder="A short memory, phrase or message…"/><small>{memoryText.length} / 160</small></label></div>}
    {edition==="wear"&&<section className="builder-section" aria-labelledby="wear-heading"><p className="section-label">MAKE IT WEARABLE</p><h2 id="wear-heading">Choose the chain length.</h2><p className="builder-note">Wear &amp; Keep includes a matching chain.</p><div className="chain-options"><Choice active={chainLength==="45 cm"} onClick={()=>setChainLength("45 cm")}>45 cm</Choice><Choice active={chainLength==="50 cm"} onClick={()=>setChainLength("50 cm")}>50 cm</Choice></div></section>}
    <section className="builder-section engraving-section" aria-labelledby="engraving-heading"><p className="section-label">BACK OF MEDALLION</p><h2 id="engraving-heading">Add a private message.</h2><div className="engraving-choices"><Choice active={backEngravingType==="none"} onClick={()=>chooseEngravingType("none")}>No engraving</Choice><Choice active={backEngravingType==="preset"} onClick={()=>chooseEngravingType("preset")}>Preset phrase</Choice><Choice active={backEngravingType==="custom"} onClick={()=>chooseEngravingType("custom")}>Custom text</Choice></div>{backEngravingType==="preset"&&<select className="phrase-select" value={presetPhrase} onChange={e=>setPresetPhrase(e.target.value)} aria-label="Preset engraving phrase"><option>Always with me</option><option>Forever loved</option><option>Always in my heart</option></select>}{backEngravingType==="custom"&&<label className="custom-engraving-field">Custom text<input maxLength={32} value={customBackText} onChange={e=>setCustomBackText(e.target.value)} placeholder="A short phrase"/><small>{customBackText.length} / 32</small></label>}</section>
    <section className="builder-section" aria-labelledby="email-heading"><p className="section-label">YOUR DETAILS</p><h2 id="email-heading">Where should we send your order updates?</h2><label>Order email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label></section>
    <aside className="live-summary" aria-labelledby="summary-heading"><p className="section-label">MADE FOR {petName ? petName.toUpperCase() : "YOUR PET"}</p><h2 id="summary-heading">One identity. One personal piece.</h2><div className="summary-lines"><div><span>Edition</span><strong>{config.name}</strong></div><div><span>Finish</span><strong>{finish==="silver"?"Silver":"Gold"}</strong></div><div><span>Pet name</span><strong>{petName||"Add their name in Step 03"}</strong></div><div><span>Years</span><strong>{years||"Not added"}</strong></div><div className="summary-wide"><span>Included items</span><ul>{includedItems.map(item=><li key={item}>{item}</li>)}</ul></div><div><span>Hair vial</span><strong>{contents.hairVial?"Included":"Skipped"}</strong></div><div><span>Memory pouch</span><strong>{contents.memoryPouch?"Included":"Skipped"}</strong></div><div><span>Memory card</span><strong>{contents.memoryCard?"Included":"Skipped"}</strong></div>{edition==="wear"&&<div><span>Chain length</span><strong>{chainLength}</strong></div>}<div className="summary-wide"><span>Back engraving</span><strong>{engravingLabel}</strong></div></div></aside>
    </div><button type="button" className="checkout-preview legacy-keepsake-builder" disabled={!ready}>Continue to checkout</button><p className="checkout-note">{ready?"Their identity and piece are ready. Payment will be connected next.":"Add a pet name and order email to continue."}</p>{onBack&&<button className="flow-back" onClick={onBack}>← Back to personalization</button>}
  </section>;
}
