"use client";
import {useEffect,useRef,useState} from "react";
import OrderBuilder from "./OrderBuilder";

const SESSION_KEY="evlenne-studio-session";

export default function Studio(){
  const input=useRef(null), previewRef=useRef(null);
  const [hydrated,setHydrated]=useState(false),[original,setOriginal]=useState(""),[medallionPortrait,setMedallionPortrait]=useState("");
  const [name,setName]=useState(""),[years,setYears]=useState(""),[step,setStep]=useState(1),[metal,setMetal]=useState("gold"),[packageType,setPackageType]=useState("complete"),[memoryText,setMemoryText]=useState(""),[email,setEmail]=useState("");
  const [zoom,setZoom]=useState(1.55),[x,setX]=useState(50),[y,setY]=useState(38),[aiPortrait,setAiPortrait]=useState(""),[aiWorking,setAiWorking]=useState(false),[error,setError]=useState("");

  useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem(SESSION_KEY)||"null");if(saved){setOriginal(saved.original||"");setMedallionPortrait(saved.medallionPortrait||"");setName(saved.name||"");setYears(saved.years||"");setStep(saved.step||1);setMetal(saved.metal||"gold");setPackageType(saved.packageType||"complete");setMemoryText(saved.memoryText||"");setEmail(saved.email||"");setZoom(saved.zoom||1.55);setX(saved.x||50);setY(saved.y||38);setAiPortrait(saved.aiPortrait||"")}}catch{}setHydrated(true)},[]);
  useEffect(()=>{if(!hydrated)return;try{sessionStorage.setItem(SESSION_KEY,JSON.stringify({original,medallionPortrait,name,years,step,metal,packageType,memoryText,email,zoom,x,y,aiPortrait}))}catch{}},[hydrated,original,medallionPortrait,name,years,step,metal,packageType,memoryText,email,zoom,x,y,aiPortrait]);

  function pick(e){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{setOriginal(String(reader.result));setAiPortrait("");setMedallionPortrait("");setError("");setStep(1)};reader.readAsDataURL(file)}
  async function removeWhiteBackground(blob){const bitmap=await createImageBitmap(blob),canvas=document.createElement("canvas");canvas.width=bitmap.width;canvas.height=bitmap.height;const ctx=canvas.getContext("2d",{willReadFrequently:true});ctx.drawImage(bitmap,0,0);const image=ctx.getImageData(0,0,canvas.width,canvas.height),d=image.data;for(let i=0;i<d.length;i+=4){const r=d[i],g=d[i+1],b=d[i+2],min=Math.min(r,g,b),max=Math.max(r,g,b);if(min>246&&max-min<10)d[i+3]=0;else if(min>226&&max-min<16)d[i+3]=Math.round(255*(246-min)/20)}ctx.putImageData(image,0,0);return canvas.toDataURL("image/png")}
  async function createArtwork(){if(!original||aiWorking)return;setAiWorking(true);setError("");try{const source=await fetch(original).then(r=>r.blob()),form=new FormData();form.append("image",source,"pet-photo.jpg");const response=await fetch("/api/create-portrait",{method:"POST",body:form});if(!response.ok){const info=await response.json().catch(()=>({}));throw new Error(info.error||"Artwork generation failed")}const blob=await response.blob();setAiPortrait(URL.createObjectURL(blob));setMedallionPortrait(await removeWhiteBackground(blob))}catch(err){setError(err.message||"We couldn't create the artwork. Please try again.")}finally{setAiWorking(false)}}
  const go=n=>{setStep(n);window.scrollTo({top:0,behavior:"smooth"})};
  return <main className="studio-flow">
    <header className="studio-header"><a href="/" className="studio-logo"><img src="/evlenne-logo.png" alt="Evlenne"/></a><p>Memorial keepsake studio <span>· Session saved</span></p></header>
    <nav className="studio-progress" aria-label="Order progress">{["Photo","Artwork","Finish"].map((label,i)=><button key={label} className={step===i+1?"active":step>i+1?"done":""} onClick={()=>i+1<step&&go(i+1)}><b>0{i+1}</b><span>{label}</span></button>)}</nav>
    {step===1&&<section className="flow-step photo-step"><p className="step">01 · PHOTO</p><h1>Start with their photograph.</h1><p className="muted">Choose a clear photo. We’ll use it to prepare laser-engraved artwork for their memorial keepsake box.</p><input ref={input} hidden type="file" accept="image/*" onChange={pick}/><button className="upload-dropzone" onClick={()=>input.current?.click()}><span className="upload-icon">↑</span><strong>{original?"Choose another photo":"Upload their photo"}</strong><small>JPG, PNG or HEIC · clear photos work best</small></button><aside className="photo-guidance"><strong>Photo guidance</strong><span>Choose a well-lit photo where their face is easy to see.</span><span>One pet per photo gives the clearest engraving.</span></aside>{original&&<div className="upload-success"><div className="upload-success-head"><span className="upload-check">✓</span><div><strong>Photo uploaded</strong><small>Ready to prepare their artwork</small></div></div><div className="original-card"><img src={original} alt="Uploaded pet"/><span>YOUR PHOTO</span></div><button className="change-photo" onClick={()=>input.current?.click()}>Choose a different photo</button></div>}{original&&<button className="flow-next" onClick={()=>go(2)}>Continue to artwork →</button>}</section>}
    {step===2&&<section className="flow-step" ref={previewRef}><p className="step">02 · ARTWORK</p><h1>Prepare their engraving.</h1>{!aiPortrait&&<><p className="muted">Generate and review the artwork that will be laser engraved on the pet pendant inside their memorial keepsake box.</p>{original&&<button className="create-art" disabled={aiWorking} onClick={createArtwork}>{aiWorking?"Creating engraving artwork…":"Generate engraving artwork"}</button>}</>}{error&&<div className="artwork-note"><strong>Artwork generation failed.</strong><br/>{error}</div>}{aiPortrait&&<><div className="portrait-review-grid"><div><p className="review-label">ENGRAVING PREVIEW</p><div className={"medallion portrait-medallion clean-preview "+(metal==="silver"?"silver-preview":"gold-preview")}>{medallionPortrait&&<img className="portrait-cutout clean-cutout" src={medallionPortrait} alt="Laser engraving artwork" style={{left:x+"%",top:y+"%",transform:"translate(-50%,-50%) scale("+zoom+")"}}/>}</div><div className="metal-switch"><button className={metal==="gold"?"active":""} onClick={()=>setMetal("gold")}>GOLD</button><button className={metal==="silver"?"active":""} onClick={()=>setMetal("silver")}>SILVER</button></div></div><div className="controls"><p className="review-label">REVIEW CROP & FINISH</p><label>Crop size<input type="range" min=".8" max="3" step=".05" value={zoom} onChange={e=>setZoom(+e.target.value)}/></label><label>Left / right<input type="range" min="25" max="75" value={x} onChange={e=>setX(+e.target.value)}/></label><label>Up / down<input type="range" min="10" max="75" value={y} onChange={e=>setY(+e.target.value)}/></label></div></div><button className="create-art secondary-action" disabled={aiWorking} onClick={createArtwork}>{aiWorking?"Creating…":"Regenerate artwork"}</button><button className="flow-next" onClick={()=>go(3)}>Continue to finish →</button></>}<button className="flow-back" onClick={()=>go(1)}>← Back to photo</button></section>}
    {step===3&&<section className="flow-step flow-order"><OrderBuilder metal={metal} setMetal={setMetal} petName={name} years={years} setPetName={setName} setYears={setYears} kind={packageType} setKind={setPackageType} memory={memoryText} setMemory={setMemoryText} email={email} setEmail={setEmail} onBack={()=>go(2)}/></section>}
  </main>
}
