"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "../../../lib/supabaseClient";
import {preparePhoto} from "../../../lib/preparePhoto";
import styles from "./paw.module.css";

export default function PawPrintPage({params}){
  const router=useRouter(),input=useRef(null);
  const [pet,setPet]=useState(null),[file,setFile]=useState(null),[preview,setPreview]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  useEffect(()=>{let live=true;(async()=>{try{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/account");return;}const {data,error:petError}=await supabase.from("pets").select("id,name,pet_assets(kind,storage_path)").eq("id",params.id).single();if(petError)throw petError;const saved=data.pet_assets?.find(asset=>asset.kind==="paw");if(saved?.storage_path){const {data:url}=await supabase.storage.from("pet-assets").createSignedUrl(saved.storage_path,3600);if(live)setPreview(url?.signedUrl||"");}if(live)setPet(data);}catch(err){if(live)setError(err.message||"We couldn’t load this pet.");}finally{if(live)setLoading(false);}})();return()=>{live=false};},[params.id,router]);
  async function choose(event){const next=event.target.files?.[0];event.target.value="";if(!next)return;if(next.size>20*1024*1024){setError("Choose an image smaller than 20 MB.");return;}setError("");try{const prepared=await preparePhoto(next);setFile(prepared.file);setPreview(prepared.url);}catch{setError("This image couldn’t be opened. Choose a JPG, PNG, WEBP or HEIC paw print photo.");}}
  async function save(){if(!file||!pet||saving)return;setSaving(true);setError("");try{const supabase=createClient();const {data:{user}}=await supabase.auth.getUser();if(!user){router.replace("/account");return;}const extension=(file.name.split(".").pop()||"jpg").toLowerCase(),path=`${user.id}/${pet.id}/paw-print.${extension}`;const {error:uploadError}=await supabase.storage.from("pet-assets").upload(path,file,{upsert:true,contentType:file.type});if(uploadError)throw uploadError;const {error:removeError}=await supabase.from("pet_assets").delete().eq("pet_id",pet.id).eq("kind","paw");if(removeError)throw removeError;const {error:assetError}=await supabase.from("pet_assets").insert({pet_id:pet.id,kind:"paw",storage_path:path,approved:true});if(assetError)throw assetError;router.push("/pets");}catch(err){setError(err.message||"We couldn’t save this paw print. Please try again.");}finally{setSaving(false);}}
  if(loading)return <main className={styles.page}><p className={styles.loading}>Loading paw print…</p></main>;
  if(error&&!pet)return <main className={styles.page}><p className={styles.error}>{error}</p><Link href="/pets" className={styles.textLink}>← Back to My pets</Link></main>;
  return <main className={styles.page}><Link href="/pets" className={styles.back}>← My pets</Link><div className={styles.intro}><p>MY PETS / PAW PRINT</p><h1>Add {pet?.name||"their"} real<br/><em>paw print.</em></h1><span>Upload a clear photo of an ink, clay, or clean paw impression. We’ll keep its unique shape and scale it to fit the piece you choose.</span></div><div className={styles.layout}><section className={styles.upload}><input ref={input} className={styles.input} type="file" accept="image/jpeg,image/png,image/webp,image/heic,image/heif" onChange={choose}/>{preview?<><div className={styles.preview}><img src={preview} alt={`${pet?.name||"Pet"} paw print`}/></div><button className={styles.secondary} onClick={()=>input.current?.click()}>Choose a different image</button></>:<button className={styles.drop} onClick={()=>input.current?.click()}><span>PAW PRINT</span><strong>Drop a paw print image here</strong><small>JPG · PNG · WEBP · HEIC · UP TO 20 MB</small><b>Choose image →</b></button>}<p className={styles.scale}>Your pet’s actual paw shape, scaled to fit the finished piece.</p></section><aside className={styles.guidance}><h2>For the clearest paw print</h2><ol><li>Use a flat, evenly lit photo.</li><li>Keep every toe pad and edge visible.</li><li>Ink or clay impressions work best.</li></ol></aside></div>{error&&<p className={styles.error}>{error}</p>}<div className={styles.actions}><button className={styles.primary} disabled={!file||saving} onClick={save}>{saving?"Saving paw print…":"Save paw print →"}</button></div></main>;
}
