"use client";
import Link from "next/link";
import {useEffect,useRef,useState} from "react";
import styles from "../homepage.module.css";
import chrome from "./SiteChrome.module.css";
import {createClient} from "../lib/supabaseClient";

function SearchIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg>}
function AccountIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5"/><path d="M5 20c.8-3.5 3-5.2 7-5.2s6.2 1.7 7 5.2"/></svg>}
function BagIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/></svg>}

export function SiteHeader(){const [user,setUser]=useState(null),[open,setOpen]=useState(false),menuRef=useRef(null);useEffect(()=>{let mounted=true;const supabase=createClient();supabase.auth.getUser().then(({data})=>{if(mounted)setUser(data.user||null)});const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(mounted)setUser(session?.user||null)});function close(event){if(!menuRef.current?.contains(event.target))setOpen(false)}document.addEventListener("pointerdown",close);return()=>{mounted=false;subscription.unsubscribe();document.removeEventListener("pointerdown",close)}},[]);async function signOut(){const supabase=createClient();await supabase.auth.signOut();setOpen(false);window.location.assign("/")}return <div className={`${styles.home} ${chrome.chrome}`}><header className={styles.siteHeader}><Link href="/" className={styles.logo}><img src="/brand/evlenne-logo-star.png" alt="Evlenne" width="2172" height="724"/></Link><nav className={styles.desktopNav} aria-label="Main"><a href="/#shop">Shop</a><a href="/#how-it-works">How It Works</a><a href="/our-story">Our Story</a></nav><div className={styles.headerActions}><button aria-label="Search"><SearchIcon/></button>{user?<div className={chrome.accountMenu} ref={menuRef}><button type="button" className={chrome.accountTrigger} aria-label="Account menu" aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><AccountIcon/></button>{open&&<div className={chrome.accountPopover} role="menu"><p>{user.email}</p><Link href="/pets" role="menuitem" onClick={()=>setOpen(false)}>My pets</Link><button type="button" role="menuitem" onClick={signOut}>Sign out</button></div>}</div>:<Link href="/account" aria-label="Sign in"><AccountIcon/></Link>}<button aria-label="Bag"><BagIcon/></button><Link href="/studio" className={styles.headerCta}>Create Your Pet</Link></div><details className={styles.mobileMenu}><summary aria-label="Open menu"><i/><i/><i/></summary><div><a href="/#shop">Shop</a><a href="/#how-it-works">How It Works</a><a href="/our-story">Our Story</a>{user?<><Link href="/pets">My Pets</Link><button type="button" onClick={signOut}>Sign out</button></>:<Link href="/account">Account</Link>}<Link href="/studio">Create Your Pet</Link></div></details></header></div>}

function SocialLinks(){return <div className={chrome.social}><span>Follow along</span><div><a href="#footer" aria-label="TikTok"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 4v10.3a3.7 3.7 0 1 1-3-3.65"/><path d="M14 4c.7 2.2 2.1 3.4 4.4 3.7"/></svg></a><a href="#footer" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="4" width="16" height="16" rx="4"/><circle cx="12" cy="12" r="3.5"/><circle cx="17.3" cy="6.8" r=".8" fill="currentColor" stroke="none"/></svg></a><a href="#footer" aria-label="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 20v-7h2.5l.5-3H14V8.2c0-.9.3-1.7 1.7-1.7H17V3.8c-.5-.1-1.4-.2-2.3-.2C12.3 3.6 11 5 11 7.5V10H8.5v3H11v7"/></svg></a></div></div>}

export function SiteFooter(){return <div className={`${styles.home} ${chrome.chrome}`}><footer className={styles.footer} id="footer"><div className={styles.footerTop}><img src="/brand/evlenne-logo-star.png" alt="Evlenne" width="2172" height="724"/><p>A personalized lifestyle brand built around the pet you love.</p><SocialLinks/></div><div className={styles.footerColumns}><div><h3>Shop</h3><a href="/#shop">Wear</a><a href="/#shop">Carry</a><a href="/#shop">Keep</a></div><div><h3>About</h3><a href="/our-story">Our Story</a><a href="/#how-it-works">How It Works</a><a href="/#faq">FAQ</a></div><div><h3>Help</h3><a href="/#contact">Contact</a><a href="/#shipping">Shipping</a><a href="/#returns">Returns</a></div></div><div className={styles.footerBottom}>© {new Date().getFullYear()} Evlenne</div></footer></div>}
