import Link from "next/link";
import { Newsreader } from "next/font/google";
import styles from "./landing.module.css";

const serif = Newsreader({ subsets: ["latin"], style: ["normal", "italic"], weight: ["400", "500"], variable: "--font-serif" });
const benefits = [["camera", "Custom from your photo", "A clear, well-lit photo of your pet."], ["pen", "AI-crafted portrait", "Refined into a clean engraving-style portrait."], ["heart", "Preview before ordering", "See the keepsake before you buy."], ["gift", "A meaningful keepsake", "Made to stay with you, always."]];
const steps = [["01", "Upload a photo", "Choose a clear photograph that feels like them.", "/products/box-flat-lay.jpg"], ["02", "We create the portrait", "We refine the artwork for a small, timeless keepsake.", "/products/box-open.jpg"], ["03", "Preview & order", "Review the details before your keepsake is made.", "/products/box-jade.jpg"]];
function BenefitIcon({ type }) { const common = { width: 30, height: 30, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 1.4, strokeLinecap: "round", strokeLinejoin: "round", "aria-hidden": true }; if (type === "camera") return <svg {...common}><path d="M4 7h3l1.5-2h7L17 7h3v12H4z" /><circle cx="12" cy="13" r="3.5" /></svg>; if (type === "pen") return <svg {...common}><path d="M5 19 19 5" /><path d="M7 5h5v5M17 19h-5v-5" /></svg>; if (type === "heart") return <svg {...common}><path d="M20.8 8.8c0 5.2-8.8 10.2-8.8 10.2S3.2 14 3.2 8.8A4.4 4.4 0 0 1 12 7a4.4 4.4 0 0 1 8.8 1.8Z" /></svg>; return <svg {...common}><path d="M4 9h16v11H4zM2 6h20v3H2zM12 6v14M12 6c-1-3-5-3.5-5-1.2C7 6.2 9 6 12 6Zm0 0c1-3 5-3.5 5-1.2C17 6.2 15 6 12 6Z" /></svg>; }

export default function Home() {
  return <div className={`${styles.page} ${serif.variable}`}>
    <header className={styles.header}><Link href="/" className={styles.brand}><img src="/evlenne-logo.png" alt="Evlenne — Memorial keepsakes" /></Link><nav className={styles.nav} aria-label="Main"><a href="#create">Create</a><button aria-label="Search" className={styles.headerIcon}><svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg></button><button aria-label="Shopping bag" className={styles.headerIcon}><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/></svg></button></nav><details className={styles.menu}><summary aria-label="Menu"><i /><i /><i /></summary><div><a href="#create">Create</a></div></details></header>
    <main>
      <section className={styles.hero} id="create"><div className={styles.heroCopy}><p className={styles.eyebrow}>A keepsake made from their photograph</p><h1>Keep them <em>close.</em></h1><p className={styles.lead}>A favorite photograph, thoughtfully transformed into laser engraving artwork and made into a personal memorial keepsake box.</p><Link href="/studio" className={styles.cta}>Create their keepsake <span>→</span></Link><p className={styles.caption}>Created from your photo · Preview before ordering</p></div><div className={styles.heroProduct} role="img" aria-label="Walnut memorial keepsake box with pendant and memory items" /></section>
      <section className={styles.benefits}>{benefits.map(([type, title, text]) => <div className={styles.benefit} key={title}><span><BenefitIcon type={type} /></span><strong>{title}</strong><small>{text}</small></div>)}</section>
      <section className={styles.keepsakes} id="keepsakes"><div className={styles.keepsakeText}><p className={styles.eyebrow}>Two timeless finishes</p><h2>Gold or <em>silver.</em></h2><p>The same heartfelt portrait, available in the finish that feels most like them.</p><Link href="/studio" className={styles.textLink}>Choose your keepsake <span>→</span></Link></div><img className={styles.pendants} src="/pendants-dogs.png" alt="Gold and silver pet portrait pendants featuring the two Evlenne dogs" /><img src="/products/box-top-view.jpg" alt="Walnut keepsake box" /></section>
      <section className={styles.how} id="how"><p className={styles.eyebrow}>From photograph to keepsake</p><h2>How it <em>works.</em></h2><p className={styles.intro}>Turn their photo into something you can keep close in just a few thoughtful steps.</p><div className={styles.stepGrid}>{steps.map(([number, title, text, image]) => <article key={number}><img src={image} alt="Walnut keepsake box detail" /><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
      <section className={styles.about} id="about"><div><p className={styles.eyebrow}>A keepsake for everyday</p><h2>Made with care <em>in Canada.</em></h2><p>Each portrait is prepared with attention to detail, so you can carry the ones you love with you, always.</p><div className={styles.made}><span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 21V8M12 12 7 9m5 3 5-4M7 9 5 5l4 1 3-4 3 4 4-1-2 5"/></svg><small>Made in Canada</small></span><span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="m12 3 8 8-8 10-8-10 8-8Z"/></svg><small>Premium materials</small></span><span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9h16v11H4zM2 6h20v3H2zM12 6v14M12 6c-1-3-5-3.5-5-1.2C7 6.2 9 6 12 6Zm0 0c1-3 5-3.5 5-1.2C17 6.2 15 6 12 6Z"/></svg><small>Thoughtful packaging</small></span></div></div><img src="/products/box-jade.jpg" alt="Open walnut keepsake box" /></section>
      <section className={styles.finalCta}><p className={styles.eyebrow}>Ready to create</p><h2>Turn their photo into <em>a keepsake.</em></h2><Link href="/studio" className={styles.cta}>Create their keepsake <span>→</span></Link></section>
    </main>
    <footer className={styles.footer}><div className={styles.footerBrand}><img src="/evlenne-logo.png" alt="Evlenne"/><p>Memorial keepsakes made to<br/>keep them close.</p></div><div className={styles.footerSocial}><span>FOLLOW ALONG</span><div><a href="#tiktok" aria-label="TikTok"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 4v10.3a3.7 3.7 0 1 1-3-3.65"/><path d="M14 4c.7 2.2 2.1 3.4 4.4 3.7"/></svg></a><a href="#instagram" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="4" y="4" width="16" height="16" rx="4"/><circle cx="12" cy="12" r="3.5"/><circle cx="17.3" cy="6.8" r=".8" fill="currentColor" stroke="none"/></svg></a><a href="#facebook" aria-label="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 20v-7h2.5l.5-3H14V8.2c0-.9.3-1.7 1.7-1.7H17V3.8c-.5-.1-1.4-.2-2.3-.2C12.3 3.6 11 5 11 7.5V10H8.5v3H11v7"/></svg></a></div></div><p className={styles.copyright}>© 2026 Evlenne. Made with care in Canada.</p></footer>
  </div>;
}
