import Link from "next/link";
import { Newsreader } from "next/font/google";
import styles from "./homepage.module.css";

const serif=Newsreader({subsets:["latin"],style:["normal","italic"],weight:["400","500"],variable:"--font-serif"});

const products=[
  ["Portrait Pendant","Wear their portrait close.",null,"Product photography placeholder"],
  ["Portrait Coin","Their portrait, made permanent.",null,"Product photography placeholder"],
  ["Leather Travel Tag","Take them wherever you go.",null,"Product photography placeholder"],
  ["Paw & Fur Keepsakes","Something unmistakably theirs.",null,"Product photography placeholder"],
];

const steps=[["01","Create your pet","Upload a favorite photo and tell us their name."],["02","We build their portrait","We turn their features into a reusable Evlenne portrait."],["03","Choose their pieces","Use the same pet identity across jewelry, keepsakes and everyday pieces."],["04","Made for them","We prepare each personalized piece individually in Canada."]];

function SearchIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></svg>}
function AccountIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="8" r="3.5"/><path d="M5 20c.8-3.5 3-5.2 7-5.2s6.2 1.7 7 5.2"/></svg>}
function BagIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/></svg>}

function Header(){return <header className={styles.siteHeader}><Link href="/" className={styles.logo}><img src="/evlenne-logo-mark.png" alt="Evlenne"/></Link><nav className={styles.desktopNav} aria-label="Main"><a href="#shop">Shop</a><a href="#how-it-works">How It Works</a><a href="/our-story">Our Story</a></nav><div className={styles.headerActions}><button aria-label="Search"><SearchIcon/></button><Link href="/account" aria-label="Account"><AccountIcon/></Link><button aria-label="Bag"><BagIcon/></button><Link href="/studio?mode=new" className={styles.headerCta}>Create Your Pet</Link></div><details className={styles.mobileMenu}><summary aria-label="Open menu"><i/><i/><i/></summary><div><a href="#shop">Shop</a><a href="#how-it-works">How It Works</a><a href="/our-story">Our Story</a><Link href="/studio?mode=new">Create Your Pet</Link></div></details></header>}

function PhotographyPlaceholder({ label, detail = "Real photography to follow" }) { return <div className={styles.photographyPlaceholder} role="img" aria-label={`${label} — photography placeholder`}><span>{label}</span><small>{detail}</small></div>; }

function Hero(){return <section className={styles.hero}><div className={styles.heroCopy}><p className={styles.eyebrow}>A PERSONALIZED WORLD BUILT AROUND YOUR PET</p><h1>Your pet.<br/><em>Made personal.</em></h1><p className={styles.heroLead}>Create their Evlenne identity once, then make it yours across pieces designed to wear, carry, keep and live with.</p><div className={styles.heroActions}><Link href="/studio?mode=new" className={styles.primaryCta}>Create Your Pet <span>→</span></Link><a href="#shop" className={styles.textCta}>Explore the Collection <span>→</span></a></div><p className={styles.reassurance}>One pet identity · A growing world of personalized pieces</p></div><div className={styles.heroVisual}><img src="/hero-wide-product-scene.png" alt="Walnut Evlenne keepsake box with a personalized pet portrait medallion" fetchPriority="high"/></div></section>}

function ProductCollection(){return <section className={styles.collection} id="shop"><div className={styles.sectionIntro}><p className={styles.eyebrow}>ONE PET. A WORLD MADE PERSONAL.</p><h2>Create them once.<br/><em>Make it theirs, everywhere.</em></h2><p>Your pet becomes a reusable Evlenne portrait — ready for jewelry, travel pieces, keepsakes and everything we create next.</p></div><div className={styles.productGrid}>{products.map(([name,subtitle,image,alt])=><Link href="/studio?mode=new" className={styles.productItem} key={name}><div className={styles.productImage}>{image?<img src={image} alt={alt}/>:<div className={styles.productPlaceholder}><span>PRODUCT PHOTOGRAPHY</span><small>Coming into focus</small></div>}</div><h3>{name}</h3><p>{subtitle}</p><span>Explore <b>→</b></span></Link>)}</div></section>}


function HowItWorks(){return <section className={styles.process} id="how-it-works"><div className={styles.centerIntro}><p className={styles.eyebrow}>THE EVLENNE PET IDENTITY</p><h2>Upload once.<br/><em>Create without starting over.</em></h2></div><div className={styles.stepGrid}>{steps.map(([number,title,copy])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>}

function Identity(){return <section className={styles.profile}><div className={styles.profileCard}><div className={styles.profileHeader}><span>MOCHI</span><small>Portrait ready</small></div><div className={styles.profileItems}><div><div className={styles.profilePlaceholder}><span>PORTRAIT</span><small>Evlenne master</small></div><strong>Portrait</strong><span>Ready</span></div><div><div className={styles.profilePlaceholder}><span>PAW PRINT</span><small>Add anytime</small></div><strong>Paw</strong><span>Optional</span></div></div></div><div className={styles.profileCopy}><p className={styles.eyebrow}>YOUR PET, NOT JUST YOUR PHOTO</p><h2>Meet your<br/><em>Pet Identity.</em></h2><p>Today, you upload a photo and we create your piece. Tomorrow, your approved Evlenne portrait can follow your pet across every new product — without starting over.</p><p>Portrait, paw and fur can become part of one personal profile built around them.</p><Link href="/studio?mode=new" className={styles.textCta}>Create Your Pet <span>→</span></Link></div></section>}

function Story(){return <section className={styles.story} id="our-story"><div className={styles.storyVisual}><img src="/our-story-pets.png" alt="Two white dogs on a soft cream blanket" loading="lazy"/></div><div className={styles.storyCopy}><p className={styles.eyebrow}>BUILT AROUND THE BOND</p><h2>For every day with them.<br/>And every day <em>after.</em></h2><p>Evlenne is for celebrating the pets beside us as much as remembering the ones we miss.</p><p>We create personal objects around one relationship: yours and theirs.</p><Link href="/our-story" className={styles.textCta}>Our Story <span>→</span></Link></div></section>}


function Beginning(){return <section className={styles.beginning} aria-labelledby="beginning-title"><p className={styles.eyebrow}>OUR BEGINNING</p><h2 id="beginning-title">It started with<br/><em>Jaerong and Minki.</em></h2><p>In 2024, we said goodbye to Jaerong and Minki. Their faces, their little habits, and the years we shared inspired Evlenne: a way to turn a photograph into something personal you can hold close.</p><p>That beginning still guides us — keepsakes that reflect an individual pet, for the pets beside us and the ones we remember.</p><Link href="/our-story" className={styles.textCta}>Our Story <span>→</span></Link></section>}


function Materials(){return <section className={styles.materials}><div className={styles.materialCopy}><p className={styles.eyebrow}>THE DETAILS MATTER</p><h2>Made to be <em>kept.</em></h2></div><div className={styles.materialList}>{["316L stainless steel","Walnut keepsake boxes","Thoughtful finishing","Made individually","Carefully packaged"].map(item=><div key={item}><span>—</span><strong>{item}</strong></div>)}</div></section>}

function Footer(){return <footer className={styles.footer}><div className={styles.footerTop}><img src="/evlenne-logo-mark.png" alt="Evlenne"/><p>A personalized lifestyle brand built around the pet you love.</p></div><div className={styles.footerColumns}><div><h3>Shop</h3><a href="#shop">Wear</a><a href="#shop">Carry</a><a href="#shop">Keep</a></div><div><h3>About</h3><a href="/our-story">Our Story</a><a href="#how-it-works">How It Works</a><a href="#faq">FAQ</a></div><div><h3>Help</h3><a href="#contact">Contact</a><a href="#shipping">Shipping</a><a href="#returns">Returns</a></div></div><div className={styles.footerBottom}>© {new Date().getFullYear()} Evlenne</div></footer>}

export default function Home(){return <div className={`${styles.home} ${serif.variable}`}><Header/><main><Hero/><ProductCollection/><Identity/><HowItWorks/><Story/><Beginning/><Materials/><section className={styles.finalCta}><p className={styles.eyebrow}>ONE PET. A WORLD MADE PERSONAL.</p><h2>Start with<br/><em>who they are.</em></h2><Link href="/studio?mode=new" className={styles.primaryCta}>Create Your Pet <span>→</span></Link></section></main><Footer/></div>}
