import Link from "next/link";
import styles from "./jewelry.module.css";
const products=[
["Petite Oval Bracelet","Petite Portrait","oval",69,"Oval Portrait Bracelet"],
["Petite Tag Bracelet","Petite Portrait","oval",65,"Petite Tag Bracelet"],
["Petite Portrait Necklace","Petite Portrait","oval",79,"Portrait Necklace"],
["Petite Portrait Coin","Petite Portrait","oval",85,"Portrait Coin Necklace"],
["Signature Face Bracelet","Signature Silhouette","face",119,"Custom Portrait Bracelet"],
["Together Bracelet","Signature Silhouette","face",149,"Two-Pet Portrait Bracelet"],
["Signature Silhouette Pendant","Signature Silhouette","face",139,"Full Silhouette Pendant"],
["Signature Portrait Ring","Signature Silhouette","face",179,"Pet Portrait Ring"]];
function Concept({kind}){return <div className={styles.visual}><svg viewBox="0 0 300 280" role="img" aria-label="Temporary illustrated jewelry concept"><defs><linearGradient id="gold" x2="1" y2="1"><stop stopColor="#fff0bf"/><stop offset=".5" stopColor="#c49c60"/><stop offset="1" stopColor="#f6dd9d"/></linearGradient></defs><path d="M10 145H103M197 145H290" stroke="#ae8c60" strokeWidth="2"/>{kind==="oval"?<ellipse cx="150" cy="145" rx="48" ry="60" fill="url(#gold)" stroke="#b59158"/>:<path d="M101 169Q99 141 117 131L120 85L149 116L179 85L184 130Q204 143 199 169Q188 204 150 206Q113 202 101 169Z" fill="url(#gold)" stroke="#b59158"/>}<g stroke="#745d3e" fill="none" strokeWidth="1.8" strokeLinecap="round"><path d="M122 144q10-8 19 0m20 0q10-8 19 0m-30 12-7 6 7 4 7-4-7-6m0 10q-9 11-19 3m19-3q9 11 19 3"/></g></svg><span>CONCEPT ART · REPLACE WITH PRODUCT PHOTOGRAPHY</span></div>}
export const metadata={title:"Fine Pet Portrait Jewelry | Evlenne"};
export default function Jewelry(){return <main className={styles.page}><section className={styles.hero}><p className={styles.kicker}>EVLENNE · FINE PET PORTRAIT JEWELRY</p><h1>A little piece of them,<br/><em>always.</em></h1><p>Made from their photograph. Made to stay close.</p><a href="#petite">Explore the collections ↓</a></section>{["Petite Portrait","Signature Silhouette"].map((name,i)=><section className={styles.content} id={i?"signature":"petite"} key={name}><div className={styles.heading}><div><p className={styles.kicker}>{i?"SIGNATURE SILHOUETTE COLLECTION":"PETITE PORTRAIT COLLECTION"}</p><h2>{i?"Uniquely, unmistakably them.":"Everyday, close to you."}</h2><p>{i?"Custom Pet Silhouettes · Signature Pieces":"Delicate Pet Portraits · Everyday Keepsakes"}</p><p className={styles.description}>{i?"Created from your pet’s unique shape, preserving the details that make them unmistakably yours.":"Timeless shapes, personalized with their portrait. Delicate pieces made for everyday wear."}</p></div><a href={i?"#signature":"#petite"} className={styles.viewAll}>View All {name} →</a></div><div className={styles.grid}>{products.filter(p=>p[1]===name).map(p=><article className={styles.card} key={p[0]}><Concept kind={p[2]}/><h3>{p[0]}</h3><p className={styles.cn}>{p[4]}</p><p className={styles.price}>CAD ${p[3]}</p></article>)}</div></section>)}<section className={styles.benefits}><div>◇ <span>From Your Photo<small>Personalized from your photo</small></span></div><div>♡ <span>Meaningful Design<small>Made with meaning</small></span></div><div>♢ <span>Quality Materials<small>Carefully selected metals</small></span></div><div>♧ <span>Thoughtful Packaging<small>Beautifully presented for gifting</small></span></div></section><p className={styles.disclaimer}>Concept designs · Products in development · Prices in CAD, subject to final material and production testing.</p></main>}