import Link from "next/link";
import styles from "./jewelry.module.css";
import JewelryFinishSwatches from "../components/JewelryFinishSwatches";
const products=[
["Petite Oval Bracelet","Petite Portrait","oval",69,"Oval Portrait Bracelet"],
["Petite Tag Bracelet","Petite Portrait","oval",65,"Petite Tag Bracelet"],
["Petite Portrait Necklace","Petite Portrait","oval",79,"Portrait Necklace"],
["Petite Portrait Coin","Petite Portrait","oval",85,"Portrait Coin Necklace"],
["Signature Face Bracelet","Signature Silhouette","face",119,"Custom Portrait Bracelet"],
["Together Bracelet","Signature Silhouette","face",149,"Two-Pet Portrait Bracelet"],
["Signature Silhouette Pendant","Signature Silhouette","face",139,"Full Silhouette Pendant"],
["Signature Portrait Ring","Signature Silhouette","face",179,"Pet Portrait Ring"]];
const imagePaths=["petite-oval-bracelet","petite-tag-bracelet","petite-portrait-necklace","petite-portrait-coin","signature-face-bracelet","together-bracelet","signature-silhouette-pendant","signature-portrait-ring"];
function ProductImage({name}){const index=products.findIndex(p=>p[0]===name);return <div className={styles.visual}><img src={`/jewelry/${imagePaths[index]}.webp`} alt={`${name} jewelry concept photograph`} loading="lazy" style={{width:"100%",height:"100%",objectFit:"cover",display:"block"}}/></div>}
export const metadata={title:"Fine Pet Portrait Jewelry | Evlenne"};
export default function Jewelry(){return <main className={styles.page}><section className={styles.hero}><p className={styles.kicker}>EVLENNE · FINE PET PORTRAIT JEWELRY</p><h1>A little piece of them,<br/><em>always.</em></h1><p>Made from their photograph. Made to stay close.</p><a href="#petite">Explore the collections ↓</a></section>{["Petite Portrait","Signature Silhouette"].map((name,i)=><section className={styles.content} id={i?"signature":"petite"} key={name}><div className={styles.heading}><div><p className={styles.kicker}>{i?"SIGNATURE SILHOUETTE COLLECTION":"PETITE PORTRAIT COLLECTION"}</p><h2>{i?"Uniquely, unmistakably them.":"Everyday, close to you."}</h2><p>{i?"Custom Pet Silhouettes · Signature Pieces":"Delicate Pet Portraits · Everyday Keepsakes"}</p><p className={styles.description}>{i?"Created from your pet’s unique shape, preserving the details that make them unmistakably yours.":"Timeless shapes, personalized with their portrait. Delicate pieces made for everyday wear."}</p></div><a href={i?"#signature":"#petite"} className={styles.viewAll}>View All {name} →</a></div><div className={styles.grid}>{products.filter(p=>p[1]===name).map(p=><article className={styles.card} key={p[0]}><ProductImage name={p[0]}/><h3>{p[0]}</h3><p className={styles.cn}>{p[4]}</p><p className={styles.price}>CAD ${p[3]}</p><JewelryFinishSwatches name={p[0]}/></article>)}</div></section>)}<section className={styles.benefits}><div>◇ <span>From Your Photo<small>Personalized from your photo</small></span></div><div>♡ <span>Meaningful Design<small>Made with meaning</small></span></div><div>♢ <span>Quality Materials<small>Carefully selected metals</small></span></div><div>♧ <span>Thoughtful Packaging<small>Beautifully presented for gifting</small></span></div></section><p className={styles.disclaimer}>Concept designs · Products in development · Prices in CAD, subject to final material and production testing.</p></main>}