import Link from "next/link";
import styles from "./jewelry.module.css";
const products=[
["Petite Oval Bracelet","Petite Portrait","oval","$59–79"],
["Petite Portrait Necklace","Petite Portrait","oval","$65–89"],
["Signature Face Bracelet","Signature Silhouette","face","$99–139"],
["Signature Silhouette Pendant","Signature Silhouette","face","$109–159"]];
function Concept({kind}){return <div className={styles.visual}><svg viewBox="0 0 300 280" role="img" aria-label="Temporary illustrated jewelry concept"><defs><linearGradient id="gold" x2="1" y2="1"><stop stopColor="#fff0bf"/><stop offset=".5" stopColor="#c49c60"/><stop offset="1" stopColor="#f6dd9d"/></linearGradient></defs><path d="M10 145H103M197 145H290" stroke="#ae8c60" strokeWidth="2"/>{kind==="oval"?<ellipse cx="150" cy="145" rx="48" ry="60" fill="url(#gold)" stroke="#b59158"/>:<path d="M101 169Q99 141 117 131L120 85L149 116L179 85L184 130Q204 143 199 169Q188 204 150 206Q113 202 101 169Z" fill="url(#gold)" stroke="#b59158"/>}<g stroke="#745d3e" fill="none" strokeWidth="1.8" strokeLinecap="round"><path d="M122 144q10-8 19 0m20 0q10-8 19 0m-30 12-7 6 7 4 7-4-7-6m0 10q-9 11-19 3m19-3q9 11 19 3"/></g></svg><span>CONCEPT ART · REPLACE WITH PRODUCT PHOTOGRAPHY</span></div>}
export const metadata={title:"Fine Pet Portrait Jewelry | Evlenne"};
export default function Jewelry(){return <main className={styles.page}><section className={styles.hero}><p className={styles.kicker}>EVLENNE / FINE PET PORTRAIT JEWELRY</p><h1>A little piece of them,<br/><em>always.</em></h1><p>Made from their photograph. Designed to stay close.</p><a href="#collections">Explore the collections ↓</a></section><section className={styles.content} id="collections"><p className={styles.kicker}>THE COLLECTIONS</p><h2>Personal in every detail.</h2><div className={styles.grid}>{["Petite Portrait","Signature Silhouette"].map((name,i)=><a className={styles.card} href={i?"#signature":"#petite"} key={name}><Concept kind={i?"face":"oval"}/><h3>{name}</h3><p>{i?"Their one-of-a-kind silhouette.":"Delicate portraits for everyday wear."}</p></a>)}</div></section>{["Petite Portrait","Signature Silhouette"].map((name,i)=><section className={styles.content} id={i?"signature":"petite"} key={name}><p className={styles.kicker}>0{i+1} / THE COLLECTION</p><h2>{name}</h2><div className={styles.grid}>{products.filter(p=>p[1]===name).map(p=><article className={styles.card} key={p[0]}><Concept kind={p[2]}/><p className={styles.kicker}>IN DEVELOPMENT</p><h3>{p[0]}</h3><p>Indicative CAD {p[3]} · Subject to material testing</p></article>)}</div></section>)}<section className={styles.end}><p className={styles.kicker}>COMING TO EVLENNE</p><h2>Made for the bond you share.</h2><p>Our jewelry collection is in development. Begin with their portrait today.</p><Link href="/studio?mode=new">Create your pet portrait →</Link></section></main>}